import React, {Component} from 'react';
import {Table, Checkbox, Button, Grid, Image, Segment, Dropdown} from "semantic-ui-react"

export const Orders = [
  {
    key: "OFTSCS",
    text: "Order of the Spicy Chicken Sandwich",
    value: "Order of the Spicy Chicken Sandwich",
    def: 12,
    hp: 1,
    arcbn: true,
    arcval: 1,
    lvl1: "<b>Spicy Touch:</b> reaching out and touching an adjacent enemy with the spice left on your fingertips. If the attack hits, it does 1d4+1 heat damage. <i>Casting Distance 5 ft</i><br> <b>Slow Heat:</b> A steady heat that slowly wears on your opponents. The enemy must make a strength-saving throw of 13 or higher. If the enemy fails the throw, they will take one point of heat damage and one additional point of heat damage after each of their turns (At level 3, this increased to three points of heat damage)<br> <b>Smokescreen:</b> A diversion tactic in which a cloud of smoke appears and temporarily blinds your opponents. Choose a point within the casting distance. All characters within a 10-foot radius of that point must make a strength-saving throw of 13 or higher. Those who fail the throw will have their movement ability reduced by half and be at a disadvantage on all rolls made that turn. Adventurers who are trained in the Art of the Chicken are often seen as magical, having a connection to otherworldly flavor and a penchant for perfection. Though those who study the Art of the Chicken can take many paths — they are all connected to abilities and powers beyond the physical realm. Characters moving into the area must make a saving throw, and characters starting their turn in the area must make an additional saving throw. This spell lasts three turns or until a different smokescreen or smoke bomb is cast. <i>Casting Distance 90ft</i>.<br>",
    lvl2: "<b>Crunch</b> Your skin hardens to help protect you from enemy assaults. You gain a resistance to all physical damage for four turns.<br> <b>True Fire:</b> An orb of flame that surrounds and protects you from outside forces for three turns. If you succeed your roll, you’ll get a +3 to your defense on projectile and magic attacks for three turns. Enemies must make an Arcana-saving throw of 14 or higher or take +2 damage to their HP when attempting to make a non-projectile physical attack for the next three turns.<br>",
    lvl3: "<b>Quick Burn:</b> This is a short blast of hot air, aka a ball of steam, into an opponent’s face. If the attack hits, it will do 1d12 heat damage. <i>Casting Distance: 60 feet</i><br> <b>Smoke Bomb:</b> An explosive diversionary tactic! After a blast of force, a cloud of smoke spreads and temporarily blinds your opponents. Choose a point within the casting distance. All characters within a 20-foot radius of that point must make a strength-saving throw of 13 or higher. Those who fail the throw will have their movement ability reduced by half and be at a disadvantage on all rolls made that turn. Those within the circle who fail their throws upon casting will take 1d6+1 force damage. Characters moving into the area must make a saving throw, and characters starting their turn in the area must make an additional saving throw. This spell lasts for three turns or until a different smokescreen or smoke bomb is cast. <i>Casting Distance: 90 feet</i><br>",
    lvl4: "<b>Flamethrower:</b> A column of flame goes out from your extended hand. If the attack hits, all characters in a straight line for 30 feet will take 2d4+1 damage<br>",
    lvl5: "<b>Unending Heat:</b> A sphere of white and blue flame engulfs an area within a 30-foot radius in all directions. All characters within that area must make a strength-saving throw of 13 or higher or take 4d6+4 heat damage. On a successful throw,they take half damage. [<i><u>This skill can only be used once between each meal.</u></i>]",
    abtclss: "Those who study the Order of the Spicy Chicken Sandwich are no strangers to heat. In fact, they thrive in it. Trained in the Art of the Spicy Chicken Sandwich, these adventurers are one with the hot climates found in parts of the nation of Freshtovia. This connection to heat flows through them. Often from desert towns, these adventurers are known for their crispy exterior, but are tender once you get close to them.",
    deets: "Base defense is 12.<br>ARC stat +1.<br>HP +1.<br>Skilled: Light armors, robes, staffs, light weapons and throwing weapons <br> Can't use: Heavy or Medium armors, shields or heavy weapons.<br>"
  },{
    key: "OFTHCS",
    text: "Order of the Homestyle Chicken Sandwich",
    value: "Order of the Homestyle Chicken Sandwich",
    def: 14,
    hp: 2,
    arcbn: true,
    arcval: 2,
    lvl1: "<b>Home Is Where the Hearth Is:</b> When not in combat, you can build a warm and comfortable fire. On an Arcana check of 14 or more, your flame’s aura can protect the group from bandits while sitting down for a meal.<br><b>Just Take a Bite:</b> If a teammate is downed by hunger, you can get them back on their feet and help them gain 1d4 HP. Your ability to create delicious food quickly is simply unmatched.<br>",
    lvl2: "<b>Add a Little Flavor to It:</b> You’re an inspiration to those around you. For their next turn, two characters of your choosing will gain advantage on their attack rolls. This spell takes automatic effect with no rolls required.<br><b>Team Crispy:</b> On an Arcana check of 12 or more, you are the source of your team’s new thick skin. All teammates within 10 feet of you for the next three turns will gain a +2 boost to their defense and a resistance to all non-magical damage.<br>",
    lvl3: "<b>Force to Be Reckoned With:</b> You send out a rally cry, reminding your enemies and the opposing realms that you are no joke — you are a force to be reckoned with. On an Arcana check of 13 or more, your entire team gains advantage on attack rolls for the next three turns and a +4 boost of temporary HP. (This can go above and beyond your character’s current HP level.) [<i><u>This attack can be used only once between meals and can only be used in battle.</u></i>]<br>",
    lvl4: "<b>Unstoppable:</b> On a successful Arcana check of 16 or more, a character of your choosing within range will gain the ability to do two actions per turn. If that character can already perform two actions as part of their own skill set, they can now do three actions per turn for the duration of this battle. This cannot be compounded.<br>",
    lvl5: "<b>Impenetrable Dome:</b> Through your eternal connection to love and family, you cast a magical dome of protection over a 10-foot radius. No attacks can pass through or take down the dome for two turns. Enemy characters can move into the dome, but they must make a 13 or higher Arcana save or take 2d6 damage. [<i><u>This attack can be used only once between meals.</u></i>]" ,
    abtclss: "Those who study the Order of the Homestyle Chicken Sandwich have a strong connection to family, friends and home. Although they can be a strong force on their own, these adventurers are often even stronger when surrounded by those they care about. Often from small towns on the outskirts of the thriving metropolis of the capital city of Freshtovia, these characters are the ultimate team players.",
    deets: "Base defense is 14.<br> ARC stat +2.<br>HP +2.<br>Skilled: Medium armor and projectile weapons.<br>Can't use: Heavy weapons, two-handed weapons or skilled weapons."
  },{
    key: "OFTGCS",
    text: "Order of the Grilled Chicken Sandwich",
    value: "Order of the Grilled Chicken Sandwich",
    def: 10,
    hp: 0,
    arcbn: true,
    arcval: 1,
    intbn: true,
    intval: 2,
    grcbn: true,
    grcval: 1,
    lvl1: "<b>Re-FRESH:</b> You guide your friends to clarity, removing any curses, status effects or magically caused weaknesses and disadvantages. <i>Casting Distance: Touch</i><br><b>A Quick Bite:</b> One teammate within casting distance will regain 1d4 of HP, thanks to you providing a quick, delicious and unexpectedly good bite to eat. <i>Casting Distance: 30 feet</i><br>",
    lvl2: "<b>Take a Bite:</b> If a teammate is downed by hunger, you can get them back on their feet and help them gain 1d6 HP. Your ability to create delicious food quickly is simply unmatched.",
    lvl3: "<b>A Large Bite:</b> One teammate within casting distance will regain 3d4 HP, thanks to you providing a bite to eat, crafted with care. <i>Casting Distance: 15 feet</i><br>",
    lvl4: "<b>Feed the Squad:</b> Each teammate will roll and regain 4d6 HP. Everything is better when you’re eating together. [<i><u>This attack can be used only once between meals.</u></i>]<br>",
    lvl5: "<b>Upsized Combo:</b> One teammate within casting distance will gain the full effects of sitting down to a meal. They will have fully regained HP and no longer be affected by status ailments, weaknesses, or disadvantages gained through combat. Through exhaustion, any enemy attacking you on their next turn will have advantage. [<i><u>This attack can be used only once between meals.</u></i>]",
    abtclss: "The Order of the Grilled Chicken Sandwich are the caregivers among those studying the Art of the Chicken; they’re always looking out for the health and well-being of themselves and those around them. Although they can fight in a pinch, they are known for their support role in important battles. The purveyors of the Grilled Chicken Sandwich have come from large cities or small towns, and from multiple climates. They train in Wendy’s Dining Sanctuaries in each city across the nation of Freshtovia.",
    deets: "Base defense is 10.<br>ARC and GRC stat +1, INT stat +2.<br>No HP bonus.<br>Skilled: Light armors (cloth/leather), robes, staffs, light weapoins and throwing weapons.<br>Can't use: Heavy or medium armors and heavy weapons."
  },{
    key: "OFTARCC",
    text: "Order of the Asiago Ranch Chicken Club",
    value: "Order of the Asiago Ranch Chicken Club",
    def: 11,
    hp: 1,
    arcbn: true,
    arcval: 2,
    grcbn: true,
    grcval: 1,
    lvl1: "<b>Re-FRESH:</b> You guide your friends to clarity, removing any curses, status effects or magically caused weaknesses and disadvantages. <i>Casting Distance: Touch</i><br><b>Home Is Where the Hearth Is:</b> When not in combat, you can build a warm and comfortable fire. On an Arcana check of 14 or more, your flame’s aura can protect the group from bandits while sitting down to a meal.<br>",
    lvl2: "<b>Team Crispy:</b> On an Arcana check of 15 or more, you are the source of your team’s new thick skin. All teammates within 10 feet of you for the next three turns will gain a +2 boost to their defense and a resistance to all non-magical damage.<br>",
    lvl3: "<b>Quick Burn:</b> This is a short blast of hot air, aka a ball of steam, into an opponent’s face. If the attack hits, it will do 1d8 heat damage. <i>Casting Distance: 60 feet</i>.<br><b>Feed the Squad:</b> Each teammate will roll and regain 2d6 HP. Everything is better when you’re eating together. [<i><u>This attack can be used only once between meals.</u></i>]<br>",
    lvl4: "<b>Flamethrower:</b> A column of flame goes out from your extended hand. If the attack hits, all characters in a straight line for 15 feet will take 2d4+1 damage",
    lvl5: "You can choose any skill from the Order of the Spicy Chicken Sandwich, Order of the Homestyle Chicken Sandwich or Order of the Grilled Chicken Sandwich to be your level 5 skill. This is a one time choice. This skill is your permanent 5th level skill.",
    abtclss: "Those who study the Order of the Asiago Ranch Chicken Club are focused on quality in all three forms of the chicken sandwich. They’re aggressive like Spicy, a team player like Homestyle and there to make you feel great like Grilled. This jack-of-all-trades mentality has made many Asiago adventurers into nomads who travel across Freshtovia to study all paths of the Art of the Chicken.",
    deets: "Base Defense 11.<br>ARC stat +2, GRC stat +1.<br> HP +1.<br>Skilled: Not extra skilled with any particular item.<br>Can't use: Can use all items."
  },{
    key: "OFTCN",
    text:"Order of the Chicken Nuggets",
    value: "Order of the Chicken Nuggets",
    def: 13,
    hp: 3,
    grcbn: true,
    grcval: 2,
    chrbn: true,
    chrval: 1,
    lvl1: "<b>Grab and Go [passive]:</b> When engaged in combat, you do not have to use an action to break out. You can move away freely without risk of attack. You can also use a bonus action to move up to twice your movement and still attack or perform another action.<br><b>Late-night Craving [passive]:</b> While attacking at nighttime, you will gain advantage on all attack and strength-saving rolls.<br>",
    lvl2: "<b>The 4-Piece Assault:</b> Displaying your advanced Grace and speed, you make four quick strikes on your opponent. Roll a d20 for each strike, and do 1d4 physical damage for each successful roll.<br>",
    lvl3: "<b>Delivery:</b> On an Arcana check of 13 or higher, you are immediately delivered to another point on the board within 90 feet of the point you are on now.<br>",
    lvl4: "<b>Snack Time [passive]:<b> Add +3 to your attack rolls on projectile or thrown weapons.<br>",
    lvl5: "<b>The Final Bite:</b> If you are currently undetected by an enemy in direct combat with a teammate, you perform the ultimate sneak attack, proving their eyes were truly bigger than their stomachs. On a successful attack roll, do 3d12+4 physical damage. [<i><u>This attack can be used only once between meals.</u></i>]",
    abtclss: "Adventurers who choose the Order of the Chicken Nuggets are often small and quick, but they pack an unexpected punch. They bring great flavor to the party and are a wonderful addition to any combo of adventurers in Freshtovia. Often overlooked at first but always remembered after, those of the Order of the Chicken Nuggets are truly undeniable with their record-breaking reputation.",
    deets: "Base Defense 13.<br>GRC stat +2, CHR stat +1. HP +3.<br>Skilled: Light armors (cloth/leahter), light weapons and throwing weapons.<br>Can't use: Heavy or medium armors and heavy weapons."
  },{
    key: "OFTB",
    text: "Order of the Baconator",
    value: "Order of the Baconator",
    def: 15,
    hp: 5,
    strbn: true,
    strval: 2,
    lvl1: "<b>Late-night Craving [passive]:</b> While attacking at nighttime, you will gain advantage on all attack and strength-saving rolls.<br><b>Fresh, Never Frozen [passive]:</b> You have resistance to all cold damage. You are truly fresh, never frozen.<br>",
    lvl2: "<b>Two Beef Patties [passive]:</b> You can dually wield any weapons that don’t require two hands.<br><b>Make It a Double [passive]:</b> You are allowed to perform two actions per turn.<br>",
    lvl3: "<b>Applewood Smoke Bomb:</b> An explosive diversionary tactic! After a blast of force, a cloud of smoke spreads and temporarily blinds your opponents. Choose a point within the casting distance. All characters within a 20-foot radius of that point must make a strength-saving throw of 13 or higher. Those who fail the throw will have their movement ability reduced by half and be at a disadvantage on all rolls made that turn. Those within the circle who fail their throws upon casting will take 1d6+1 force damage. Characters moving into the area must make a saving throw, and characters starting their turn in the area must make an additional saving throw. This spell lasts for three turns or until a different smokescreen or smoke bomb is cast. <i>Casting Distance: 90 feet.</i><br>",
    lvl4: "<b>Undefeated:</b> On a successful strength roll of 14 or higher, take zero damage throughout the next turn. You cannot use this on a turn with other actions. [<i><u>This attack can be used only once between meals.</u></i>]<br>",
    lvl5: "<b>Six Strips of Bacon:</b> On one successful attack roll, make six concurrent attacks. These can be with the same weapon, or you can switch between weapons on each attack. If you fail the attack roll, you lose your next turn recovering from the exerted effort. [<i><u>This attack can be used only once between meals.</u></i>]",
    abtclss: "The Order of the Baconator is reserved for some real meaty adventurers. These characters are large and beefy warriors known for their size and strength. Many attempt to go toeto-toe with a Baconator, but few conquer them.",
    deets: "Base Defense is 15.<br>STR stat +2.<br>HP +5.<br>Skilled: Medium armor, heavy armor and heavy weapons.<br>Can't use: Light armor, staffs, items granting new magical skills or projectile weapons."
  },{
    key: "OFTJBC",
    text: "Order of the Jr. Cheese Burger",
    value: "Order of the Jr. Cheese Burger",
    def: 13,
    hp: 2,
    grcbn: true,
    grcval: 2,
    strbn: true,
    strval: 2,
    lvl1: "<b>Combo Buddies [passive]:</b> At any point a teammate is within 10 feet of you, both you and the teammate gain a +1 on strength-saving rolls. The +1 does not stack with multiple teammates.<br><b>Fresh, Never Frozen [passive]:</b> You have resistance to all cold damage. You are truly fresh, never frozen.<br>",
    lvl2: "<b>Clapback [passive]:</b> If you are successfully attacked by more than one enemy in a single turn, you will clapback at each enemy after the first. They will take 1d4 of physical damage each in retaliation.<br>",
    lvl3: "<b>Bring It:</b> On a Charm check of 13 or higher, all enemy attacks this turn will be drawn to you. This partners well with the passive clapback skill.<br>",
    lvl4: "<b>Plus Up Combo:</b> You hold your turn until a successful attack from a teammate and add an additional 1d6 physical damage to their attack, making it the perfect combo. If none of your teammates makes a successful attack this turn, this added bonus is lost.<br>",
    lvl5: "<b>Ultimate Snackdown:</b> It’s time to layeth the snacketh down on some jabronis. This attack hits all enemies currently on adjacent squares to you. On a successful attack roll, they each take 3d12+5 damage. On an unsuccessful attack roll, you take 4d4 damage. (Attack roll is based on the enemy touching you with the lowest Defense stat.) [<i><u>This attack can be used only once between meals.</u></i>]",
    abtclss: "Tight, compact and packs a punch. The Order of the Jr. Bacon Cheeseburger is for the efficient warrior; no movement or moment is wasted. These characters appreciate the great flavor of many things coming together in one tight space.",
    deets: "Base Defense 13.<br>GRC and STR stat +2. HP +2. Skilled: Medium armor, heavy armor, heavy weapons and crossbows.<br>Can't use: Light armor, staffs or items granting new magical skills."
  },{
    key: "OFTDD",
    text: "Order of the Dave's Double",
    value: "Order of the Dave's Double",
    def: 14,
    hp: 4,
    strbn: true,
    strval: 1,
    grcbn: true,
    grcval: 1,
    chrbn: true,
    chrval: 1,
    lvl1: "<b>Fresh, Never Frozen [passive]:</b> You have resistance to all cold damage. You are truly fresh, never frozen.<br><b>Two Beef Patties [passive]:</b> You can dually wield any weapons that don’t require two hands.<br>",
    lvl2: "<b>Make It a Double [passive]:</b> You are allowed to perform two actions per turn.<br>",
    lvl3: "<b>Classic Double [passive]:</b> If your attack knocks an opponent out, you immediately gain an extra action.<br>",
    lvl4: "<b>Beefy Boi:</b> On a Charm check of 14 or higher, all members of the party who have chosen the Order of the Beef will gain a +2 to their Defense stat for the next four turns.<br>",
    lvl5: "<b>Does That Complete Your Order?:</b> When an opponent has less than 25% of their health, they will become completely full and pass out on a successful strength roll of 16 or higher. [<i><u>This attack can be used only once between meals.</u></i>]",
    abtclss: "The Order of the Dave’s Double is for the truly classic adventurers. As the truest purveyors of the freshest beef, their legend precedes them wherever they go.",
    deets: "Base Defense 14.<br>STR, GRC and CHR stat +1.<br>HP +4.<br>Skilled: Medium armor, heavy armor and heavy weapons.<br>Can't use: Light armor, staffs, items granting new magical skills."
  },{
    key: "OFTDS",
    text: "Order of the Double Stack",
    value: "Order of the Double Stack",
    def: 13,
    hp: 2,
    grcbn: true,
    grcval: 2,
    strbn: true,
    strval: 2,
    lvl1: "<b>Fresh, Never Frozen [passive]:</b> You have resistance to all cold damage. You are truly fresh, never frozen.<br><b>Two Beef Patties [passive]:</b> You can dually wield any weapons that don’t require two hands.<br>",
    lvl2: "<b>Combo Buddies [passive]:</b> At any point a teammate is within 10 feet of you, both you and the teammate gain a +1 on strength-saving rolls. The +1 does not stack with multiple teammates.<br>",
    lvl3: "<b>Make It a Double [passive]:</b> You are allowed to perform two actions per turn.<br><b>Late-night Craving [passive]:</b> While attacking at nighttime,you will gain advantage on all attack and strength-saving rolls.<br>",
    lvl4: "<b>Plus Up Combo:</b> You hold your turn until a successful attack from a teammate and add an additional 1d6 physical damage to their attack, making it the perfect combo. If none of your teammates makes a successful attack this turn, this added bonus is lost.<br>",
    lvl5: "Double Stackdown: It’s time to layeth the Double Stackdown on some jabronis. This attack hits all enemies currently on adjacent squares to you. On a successful attack roll, they each take 4d8+4 damage. On an unsuccessful attack roll, you take 4d4 damage. (Attack roll is based on the enemy touching you with the lowest Defense stat.) [This attack can be used only once between meals.]",
    abtclss: "Perhaps more compact than the Classic Dave’s Double, those of the Order of the Double Stack have truly gained a name in their own right. Often the perfect complement to the combo of your party, the Double Stack can also stand on its own in the face of hunger.",
    deets: "Base Defense is 13.<br>GRC and STR stat +2.<br>HP +2.<br>Skilled: Medium armor, heavy armor, heavy weapons and crossbows.<br>Can't use: Light armor, staffs or items granting new magical skills."
  },{
    key: "OFTF",
    text: "Order of the Frosty",
    value: "Order of the Frosty",
    def: 11,
    hp: 0,
    arcbn: true,
    arcval: 1,
    grcbn: true,
    grcval: 2,
    lvl1: "<b>Little Spoon:</b> Any number of enemies within 20 feet of you must make an Arcana save of 12 or higher or feel a sense of great friendship toward you. They will not attack you unless you provoke or attack them first. [<i><u>This attack can be used only once between meals.</u></i>]<br><b>Charm [passive]:</b> Party members you are near during conversations will have a +1 boost to all of their Charm rolls, because your Charm radiates onto those around you.<br>",
    lvl2: "<b>Two Spoons:</b> On a successful Arcana roll of 14 or higher, you create a mirage that will draw the attacks of your enemies on their next turn so you can break out from combat undetected. This mirage cannot speak or interact with others, but it can be used beyond combat.<br>",
    lvl3: "<b>Sweet Surprise:</b> Choose a teammate. On an Arcana roll of 13 or higher, all damage they take on the enemy’s next turn will actually be applied as healing. If you fail this roll, all damage they take will be doubled on the enemy’s next turn. One way or another, someone is in for a sweet surprise.<br>",
    lvl4: "<b>Big Spoon:</b> Enemies within 60 feet of you must make an Arcana save of 14 or higher or feel a sense of great friendship toward you. If they critically fail this roll [roll a 1], they will fall asleep in a sense of overwhelming comfort. They will not attack you unless you provoke or attack them first. [<i><u>This attack can be used only once between meals.</u></i>]<br>",
    lvl5: "<b>A Nice Deep Breath:</b> The enemy is frozen in time for the next turn. You can heal, attack or move around them however you please, and they will remain frozen until their next turn. Outside of combat, this attack will freeze a character for up to one minute. [<i><u>This attack can be used only once between meals.</u></i>]",
    abtclss: "Embracing a near magical sweetness with powers that seem ethereal, the Order of the Frosty is perfected in Freshtovia’s only cold zone — a zone that never breaks down and is always there when the citizens need it. Adventurers who study the Order of the Frosty are smooth, sweet and known to brighten the day of anyone who embraces them.",
    deets: "Base Defense is 11.<br>ARC stat +1, GRC stat +2.<br>No HP bonus.<br>Skilled: Fancy clothing, throwing weapons and light weapons.<br>Can't use: Heavy armor or heavy weapons."
  },{
    key: "OFTFF",
    text: "Order of the French Fries",
    value: "Order of the French Fries",
    def: 12,
    hp: 2,
    grcbn: true,
    grcval: 1,
    chrbn: true,
    chrval: 2,
    lvl1: "<b>The Frosty Dip [passive]:</b> If you are within 10 feet of someone who has chosen the Order of the Frosty, you both gain advantage on all skill rolls.<br><b>Grab and Go [passive]:</b> When engaged in combat, you do not have to use an action to break out. You can move away freely without risk of attack. You can also use a bonus action to move up to twice your movement and still attack or perform another action.<br>",
    lvl2: "<b>A Quick Bite:</b> One teammate within casting distance will regain 1d4 HP, thanks to you providing a quick, delicious and salty bite to eat. <i>Casting Distance: 30 feet</i>",
    lvl3: "<b>Snack Time [passive]:</b> Add +2 to your attack rolls on projectile or thrown weapons.<br>",
    lvl4: "<b>Plus Up Combo:</b> You hold your turn until a successful attack from a teammate and add an additional 1d6 physical damage to their attack, making it the perfect combo. If none of your teammates makes a successful attack this turn, this added bonus is lost.<br>",
    lvl5: "<b>Bottom of the Bag:</b> You reach deep inside. It’s often said what’s left at the bottom of the bag is the best bite. Each fry inspires your salty fury. A successful attack roll will result in 12d4+4 physical damage. [<i><u>This attack can be used only once between meals.</u></i>]",
    abtclss: "The ultimate sidekick in all situations. No party is truly complete without someone who has studied in the Order of the French Fries. You are a bit salty, and can be a bit saucy, too. Everyone loves french fries. Everyone.",
    deets: "Base Defense is 12.<br>GRC stat +1, CHR stat +2.<br>HP + 2.<br>Skilled: Light armor, throwing weapons and light weapons.<br>Can't use: Heavy armor or heavy weapons."
  },{
    key: "OFTBF",
    text: "Order of the Baconator Fries",
    value: "Order of the Baconator Fries",
    def: 13,
    hp: 2,
    strbn: true,
    strval: 1,
    chrbn: true,
    chrval: 2,
    lvl1: "<b>Grab and Go [passive]:</b> When engaged in combat, you do not have to use an action to break out. You can move away freely without risk of attack. You can also use a bonus action to move up to twice your movement and still attack or perform another action.<br>",
    lvl2: "<b>Snack Time [passive]:</b> Add +1 to your attack rolls on projectile or thrown weapons.<br>",
    lvl3: "<b>Applewood Smoke Bomb:</b> An explosive diversionary tactic! After a blast of force, a cloud of smoke spreads and temporarily blinds your opponents. Choose a point within the casting distance. All characters within a 20-foot radius of that point must make a strength-saving throw of 13 or higher. Those who fail the throw will have their movement ability reduced by half and be at a disadvantage on all rolls made that turn. Those within the circle who fail their throws upon casting will take 1d6+1 force damage. Characters moving into the area must make a saving throw, and characters starting their turn in the area must make an additional saving throw. This spell lasts for three turns or until a different smokescreen or smoke bomb is cast. <i>Casting Distance: 90 feet</i><br>",
    lvl4: "<b>Plus Up Combo:</b> You hold your turn until a successful attack from a teammate and add an additional 1d6 physical damage to their attack, making it the perfect combo. If none of your teammates makes a successful attack this turn, this added bonus is lost.<br>",
    lvl5: "<b>Totally Baconator’d:</b> You’re about to go full Baconator. You never go full Baconator. The enemy is overcome with the cheesy, meaty essence in your attack. On a successful strength roll of 15 or higher, all enemies within 15 feet of you will take 4d8 physical damage and have a disadvantage on their attack rolls for the next three turns. [<i><u>This attack can be used only once between meals.</u></i>]",
    abtclss: "Those within the Order of the Baconator Fries know how to crank everything to 11. They’re always looking to take their experiences to a higher and higher level. They are close in style with the Order of the French Fries, but are no strangers to getting into a meaty situation. These characters are bold, boisterous and strong.",
    deets: "Base Defense is 13.<br>STR stat +1, CHR stat +2.<br>HP +2.<br>Skilled: Able to use any armor or weapon though no skill bonus is added.<br>Can't use: Can use all items."
  },{
    key: "OFTC",
    text: "Order of the Chili",
    value: "Order of the Chili",
    def: 11,
    hp: 1,
    arcbn: true,
    arcval: 2,
    intbn: true,
    intval: 1,
    lvl1: "<b>The True Classic [passive]:</b> You have been around Freshtovia for what seems like many lifetimes, and you’ve seen many trends come and go. You remember almost everything about its history. When trying to gain information about an area, add a +1 to all Intelligence rolls.<br><b>A Quick Bite:</b>One teammate within casting distance will regain 1d4 HP, thanks to you providing a quick, delicious and warm bite to eat.<br>",
    lvl2: "<b>Little Spoon:</b> Any number of enemies within 20 feet of you must make an Arcana save of 12 or higher or feel a sense of great friendship toward you. They will not attack you unless you provoke or attack them first. [<i><u>This attack can be used only once between meals.</u></i>]<br><b>Combo Buddies [passive]:</b> At any point a teammate is within 10 feet of you, both you and the teammate gain a +1 on strength-saving rolls. The +1 does not stack with multiple teammates.<br>",
    lvl3: "<b>Chili Seasoning:</b> A packet of spice blasts the opponent, leaving them hot and sweaty. If the attack hits, it will do 1d12+2 heat damage<br>",
    lvl4: "<b>Force to Be Reckoned With:</b> You send out a rally cry, reminding your enemies and the opposing realms that you are no joke — you are a force to be reckoned with. On an Arcana check of 13 or more, your entire team gains advantage on attack rolls for the next three turns and a +4 boost of temporary HP. (This can go above and beyond your character’s current HP level.) [<i><u>This attack can be used only once between meals and can only be used in battle.</u></i>]<br>",
    lvl5: "<b>Slow Simmer:</b> On an Arcana check of 15 or higher, an enemy of your choosing will start to feel the slow, simmering heat of your power. This turn they’ll take 1d4 magical damage. Next turn, it’ll be 1d6. The next turn, 1d8. The next turn, 1d10. The next turn, 1d12. On the final turn, roll a percentile using 10-sided die (roll two 10-sided die and use one to represent the first digit, one to represent the second) and do this much magical damage. [<i><u>This attack can be used only once between meals.</u></i>]",
    abtclss: "The Order of the Chili is a slow yet passionate path. The simmer of life allows the spice and flavor of adventure to flow through those truly indoctrinated in the ways of the Chili. They’re rarely imitated and never duplicated. Good luck finding a master of this path outside Freshtovia.",
    deets: "Base Defense is 11.<br>INT stat +1, ARC stat +2.<br>HP +1.<br>Skilled: Light armor and finesse weapons.<br>Can't use: Heavy armor, throwing weapons or projectile weapons."
  },{
    key: "OFTBP",
    text: "Order of the Baked Potato",
    value: "Order of the Baked Potato",
    def: 13,
    hp: 1,
    lvl1: "<b>Salt of the Earth [passive]:</b> When an encounter is taking place outside, add an additional +1 to all Arcana rolls.<br><b>Hearty Fulfillment:</b> On a successful Arcana roll of 12 or higher, you and friends within 20 feet of you will have raised spirits, gaining advantage on attack rolls for the next two turns.<br>",
    lvl2: "<b>Root of the Problem:</b> You place your hands on the ground and connect with the planet. On an Arcana check of 13 or higher, you’ll deal 1d6+3 physical damage to an enemy who is attacked by the ground beneath their feet.<br><b>A Warm Bite:</b> You share a warm, satisfying comfort. Upon touch, one teammate will gain 1d4 HP at the start of their next two turns.<br>" ,
    lvl3: "<b>Twice Baked [passive]:</b> When an action is successful, you gain a second action during your turn. You do not gain additional actions beyond the second.<br>",
    lvl4: "<b>Plus Up Combo:</b> You hold your turn until a successful attack from a teammate and add an additional 1d6 physical damage to their attack, making it the perfect combo. If none of your teammates makes a successful attack this turn, this added bonus is lost.<br>",
    lvl5: "<b>Fully Loaded:</b> It’s time to load someone up with all the fixins, because they’re fixin’ to fight. On an Arcana check of 15 or higher, a character of your choosing will gain advantage on all rolls, a +2 to each stat, including defense, and a +2 damage to each attack for the next five turns. [<i><u>This attack can be used only once between meals.</u></i>]",
    abtclss: "While relative to those who have studied the Order of the French Fries, those in the Order of the Baked Potato are more in tune with the world around them. Connected to nature through their very roots, the Baked Potato characters are a one-of-a-kind talent; knockoffs are rarely found in the other nations in the realm of Beef ’s Keep.",
    deets: "Base Defense is 13.<br>STR stat +1, ARC stat +2.<br>HP +1.<br>Skilled: Heavy armor, throwing weapons and projectile weapons.<br>Can't use: Light armor or finesse weapons."
  }
]


export default Orders
